<?php

?>
<script type="text/javascript">
//<![CDATA[

axjaxRedirection= function(url)
{
<?php if ($this->getHtmlJsonKey()): ?>

    var request = new Ajax.Request(url, {
        method:'get',
        evalScripts:true,
        onSuccess: function(transport) {
            response={};
            if(transport.responseJSON) {
                response = transport.responseJSON;
            } else if (transport.responseText)  {
                response = {<?php echo $this->getHtmlJsonKey() ?>:transport.responseText}
            } else {
                response = {<?php echo $this->getHtmlJsonKey() ?>:'No result'};
            }

            if(response.<?php echo $this->getHtmlJsonKey() ?>) {
                $('<?php echo $this->getAjaxAnchor() ?>').update(response.<?php echo $this->getHtmlJsonKey() ?>);
            }
        }
    });

<?php else:?>
    var request = new Ajax.Updater('<?php echo $this->getAjaxAnchor() ?>',
            url,
            {
                method: 'get',
                evalScripts:true,
            }
        );
<?php endif;?>
}

$$('div.pager a').each(function(elem) {
    Event.observe(elem,'click',function(event) {
        var element = Event.element(event);
        axjaxRedirection(element.readAttribute('href'));
        Event.stop(event);
     });
});

$$('div.pager select').each(function(elem) {
    elem.writeAttribute('onchange', '');
    Event.observe(elem,'change',function(event) {
        var element = Event.element(event);
        axjaxRedirection(element.value);
        Event.stop(event);
     });
});

//]]>
</script>